#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <git ras_branch> <docker_tag>"
  exit 1
fi

dependecies_properties_path=../src/main/resources/dependencies.properties
common_pattern="common.git\="
as_pattern="authentication-service.git\="

ras_branch=$1
docker_tag=$2
common_branch=$(grep $common_pattern $dependecies_properties_path | awk '{split($0,a,"$common_pattern"); print a[2]}')
as_branch=$(grep $as_pattern $dependecies_properties_path | awk '{split($0,a,"$as_pattern"); print a[2]}')

sudo docker build --build-arg RAS_BRANCH=$ras_branch --build-arg AS_BRANCH=$as_branch \
 --build-arg COMMON_BRANCH=$common_branch --no-cache -t fogbow/resource-allocation-service:$docker_tag .

