package org.fogbowcloud.manager.core.models;

public enum ErrorType {

    UNAUTHORIZED, NOT_FOUND, BAD_REQUEST, QUOTA_EXCEEDED,
    METHOD_NOT_ALLOWED, NOT_ACCEPTABLE, NO_VALID_HOST_FOUND, FORBIDDEN, INTERNAL_SERVER_ERROR;
}
